image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/daikon-fe-lab:$CI_COMMIT_REF_NAME

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
  only:
    - lab-main

push:
  stage: push
  script:
    - docker push $IMAGE_TAG
  only:
    - lab-main
