export const EventMapper = {
  GeneCreatedEvent: "New Gene",
  GeneUpdatedEvent: "Gene Update",
  GeneCrispriStrainAddedEvent: "New Crispri Strain",
  GeneCrispriStrainUpdatedEvent: "Crispri Strain Update",
  GeneEssentialityAddedEvent: "New Essentiality",
  GeneEssentialityUpdatedEvent: "Essentiality Update",
  GeneHypomorphAddedEvent: "New Hypomorph",
  GeneHypomorphUpdatedEvent: "Hypomorph Update",
  GeneProteinActivityAssayAddedEvent: "New Protein Activity Assay",
  GeneProteinActivityAssayUpdatedEvent: "Protein Activity Assay Update",
  GeneProteinProductionAddedEvent: "New Protein Production",
  GeneProteinProductionUpdatedEvent: "Protein Production Update",
  GeneResistanceMutationAddedEvent: "New Resistance Mutation",
  GeneResistanceMutationUpdatedEvent: "Resistance Mutation Update",
  GeneUnpublishedStructuralInformationAddedEvent:
    "New Unpublished Structural Information",
  GeneUnpublishedStructuralInformationUpdatedEvent:
    "Unpublished Structural Information Update",
  GeneVulnerabilityAddedEvent: "New Vulnerability",
  GeneVulnerabilityUpdatedEvent: "Vulnerability Update",
  TargetCreatedEvent: "New Target",
  TargetUpdatedEvent: "Target Update",
  ScreenCreatedEvent: "New Screen",
  ScreenUpdatedEvent: "Screen Update",
  HitCollectionCreatedEvent: "New Hit Collection",
  HitCollectionUpdatedEvent: "Hit Collection Update",
  HitAddedEvent: "New Hits",
  HaCreatedEvent: "New HA",
  HaUpdatedEvent: "HA Update",
  HaDeletedEvent: "HA Deletion",
  HaCompoundEvolutionAddedEvent: "New Compound Evolution for HA",
  HaCompoundEvolutionUpdatedEvent: "Compound Evolution Update for HA",
  ProjectCreatedEvent: "New Project",
  ProjectUpdatedEvent: "Project Update",
  ProjectCompoundEvolutionAddedEvent: "New Compound Evolution for Project",
  ProjectCompoundEvolutionUpdatedEvent: "Compound Evolution Update for Project",
};
