name: DAIKON_frontend_workflow

# !TODO! Create new Github Actions secrets and assign the secret.* value here to these env assignments:
env:
  # These can be left inline and changed as needed  (if only one pipeline per env)
  ENVIRONMENT: prd
  APP_VERSION: 1.0.0

on:
  workflow_dispatch:
#  push:
#    branches:
#    - v0.16.0
#  pull_request:
#    branches:
#    - v0.16.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      
      - name: 'Get secrets'
        id: azure-keyvault
        run: |
          secrets_get=(AZURE-CLIENT-ID AZURE-TENANT-ID AZURE-RESOURCE-GROUP github-actions-registry-login-server github-actions-registry-username github-actions-registry-password)
          for secret_get in ${secrets_get[@]}
          do
            value=$(az keyvault secret show --name $secret_get --vault-name daikon-prd-kv --query value --output tsv)
            echo "::add-mask::$value"
            echo "$secret_get=$value" >> $GITHUB_OUTPUT
          done
        
      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ steps.azure-keyvault.outputs.github-actions-registry-login-server }}
          username: ${{ steps.azure-keyvault.outputs.github-actions-registry-username }}
          password: ${{ steps.azure-keyvault.outputs.github-actions-registry-password }}
      - run: |
          echo 'export const appConfig = {
          REACT_APP_MSAL_CLIENT_ID: "${{ steps.azure-keyvault.outputs.AZURE-CLIENT-ID }}",
          REACT_APP_WEB_API_BASE_URI: "https://daikon-${{ env.ENVIRONMENT }}-backend.azurewebsites.net/api/",
          REACT_APP_MSAL_CLIENT_SCOPE: "api://${{ steps.azure-keyvault.outputs.AZURE-CLIENT-ID }}/access_as_user",
          REACT_APP_MSAL_TENANT_AUTHORITY_URI: "https://login.microsoftonline.com/${{ steps.azure-keyvault.outputs.AZURE-TENANT-ID }}",
          REACT_APP_MSAL_CACHE_LOCATION: "sessionStorage",
          REACT_APP_MSAL_AUTH_STATE_IN_COOKIE: "false",
          REACT_APP_MSAL_LOGIN_REDIRECT_URI: "https://daikon-${{ env.ENVIRONMENT }}-frontend.azurewebsites.net/" };
          export const appVersion = {
              release: "v0.1.2",
              stream: "Enterprise",
              channel: "Beta" };' > ./src/config.js

          docker build . -t ${{ steps.azure-keyvault.outputs.github-actions-registry-login-server }}/daikon-frontend:${{ env.APP_VERSION }}-${{ github.sha }}
          docker push ${{ steps.azure-keyvault.outputs.github-actions-registry-login-server }}/daikon-frontend:${{ env.APP_VERSION }}-${{ github.sha }}
      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ steps.azure-keyvault.outputs.AZURE-RESOURCE-GROUP }}
          dns-name-label: ${{ steps.azure-keyvault.outputs.AZURE-RESOURCE-GROUP }}${{ github.run_number }}
          image: ${{ steps.azure-keyvault.outputs.github-actions-registry-login-server }}/daikon-frontend:${{ env.APP_VERSION }}-${{ github.sha }}
          registry-login-server: ${{ steps.azure-keyvault.outputs.github-actions-registry-login-server }}
          registry-username: ${{ steps.azure-keyvault.outputs.github-actions-registry-username }}
          registry-password: ${{ steps.azure-keyvault.outputs.github-actions-registry-password }}
          name: daikon-frontend
          location: "west us 2"
      #- name: "Publish Web App"
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: '${{ env.APP_SERVICE_NAME }}'
      #    images: '${{ steps.azure-keyvault.outputs.REGISTRY_SERVER }}/daikon-frontend:${{ env.APP_VERSION }}-${{ github.sha }}'
